### PR TITLE
Catch error before infinite copy

### PR DESCRIPTION
**Pull request by m-m-adams**
Reliably freezes with error on #2151 before the infinite memcpy

It is extremely unclear why but popupMaxX and popupMaxY appear to have garbage in them

I'm not familiar with the image code at all so I'm going to stop here and hope someone else picks it up

### CODE REVIEW

**Comment by nikodemus** [comment]
Since they're globals they're pretty ripe for memory overwrites - and a different layout between relaease and relwithdebinfo explains why this doesn't happen with both.

Trying to find out what else is near them in memory might give a clue, but textually `ConsoleItems` is nearby, and if `drawConsoleTopLine` is called with `numConsoleItems = 0` it would underflow, possibly causing this?

**Comment by m-m-adams** [comment]
image

They're in the declared order so it's probably a logic bug somewhere, otherwise all 4 would be garbage

**Comment by m-m-adams** [comment]
> If nothing else, adding a check for `numConsoleItems > 0` to `drawConsoleTopLine` might be worth it?

That seems to stop the bug entirely which I think implies that there's UB somewhere

**Comment by m-m-adams** [comment]
@nikodemus @saphire_arches the closest array looks to be the console canvas itself, so probably an out of bounds write in one of the console rendering routines

**Comment by m-m-adams** [comment]
Gonna merge this, want to rule out that this is all the freezes and there aren't multiple causes

**Pull request merged**
