### PR TITLE
[DRAFT] Set currentClip on clip create, even if clip is not entered

### PR DESCRIPTION
**Pull request by cowboy**
Per discussion in discord and comment https://github.com/SynthstromAudible/DelugeFirmware/pull/970#pullrequestreview-1820269660

### CODE REVIEW

**Comment by Queroland** [comment]
Hey,
I once had a similar problem with velocities and patch cables and I wrote a C# program to set patches and volume for all my synth programs at once.. I only runs on windows..but you can set all patches at once..check it out here:
[(https://forums.synthstrom.com/discussion/4247/deluge-xml-fixer-and-with-set-volumes/p1?new=1)]

**Comment by cowboy** [comment]
> Hey, I once had a similar problem with velocities and patch cables and I wrote a C# program to set patches and volume for all my synth programs at once.. I only runs on windows..but you can set all patches at once..check it out here: [https://forums.synthstrom.com/discussion/4247/deluge-xml-fixer-and-with-set-volumes/p1?new=1](url)

I'm not sure I understand, how is that relevant to this PR? Thanks!

**Comment by m-m-adams** [comment]
> > Hey, I once had a similar problem with velocities and patch cables and I wrote a C# program to set patches and volume for all my synth programs at once.. I only runs on windows..but you can set all patches at once..check it out here: [https://forums.synthstrom.com/discussion/4247/deluge-xml-fixer-and-with-set-volumes/p1?new=1](url)
> 
> I'm not sure I understand, how is that relevant to this PR? Thanks!

I think that was intended for the PR about changing the default modulation settings

**Comment by m-m-adams** [comment]
2 things:

1. Rows mode is not handled but should have the same behaviour
2. I think it's cleaner to move the currentClip change to press as well, as is there is different behaviour between first creating a clip and pressing on an existing clip. The addition would be setting currentClip here https://github.com/SynthstromAudible/DelugeFirmware/blob/a89de9a577dfcd0d038b16961198620a8ddc8e10/src/deluge/gui/views/session_view.cpp#L3316  and here https://github.com/SynthstromAudible/DelugeFirmware/blob/a89de9a577dfcd0d038b16961198620a8ddc8e10/src/deluge/gui/views/session_view.cpp#L615 if a clip is returned

**Comment by cowboy** [comment]
> * Rows mode is not handled but should have the same behaviour

I don't use Rows mode, can you give me an idea of what needs to change?

**Comment by m-m-adams** [comment]
I just mean the same addition but in the equivalent spot in the non-grid session code, which I think is the default path of the handle button function

**Comment by m-m-adams** [comment]
Handled by #1178

**Pull request closed without merging**
