### PR TITLE
Implement Universal SysEx Identity response

### PR DESCRIPTION
**Pull request by pmatila**
Be a good MIDI citizen and implement standard identity request (f07e7f0601f7) and response with manufacturer ID, device ID + firmware version string.

The first commit is just a minor refactor for const correctness.

### CODE REVIEW

**Review by sapphire-arches — APPROVED** [review]
Assuming you've tested this query with something that sends the standard request and interprets the response, this LGTM. Thanks for the contribution!

**Comment by pmatila** [comment]
Tested with a local Python script, yes. I can add a dbt task for testing this if you'd prefer.

**Comment by sapphire-arches** [comment]
good enough for me!

**Comment by pmatila** [comment]
Eep, actually don't merge! I just realized the standard response has a stricter format than implemented here.

**Comment by sapphire-arches** [comment]
whoops, sorry. please create a follow-up, I don't think having a broken implementation will create any problems between now and whenever that's merged.

**Comment by pmatila** [comment]
Yeah no kittens will be killed by this, I'll followup. Apologies for the mess of a premature PR :-/

**Pull request merged**
