### PR TITLE
Github pages: init

### PR DESCRIPTION
**Pull request by bobtwinkles**
This adds a Github pages site, based on nextjs static site rendering, which provides a nicer interface for downloading the latest community builds. A version of the site (built for commits from my fork) is online at https://bobtwinkles.github.io/DelugeFirmware/.

### CODE REVIEW

**Comment by bobtwinkles** [comment]
A followup PR will pull the latest build for each PR that still has valid artifacts, but I want to get this at least sort of in-place before going absolutely wild with it.

**Comment by sichtbeton** [comment]
Where can (besides your page example) this be found?

**Comment by jamiefaye** [comment]
I put this one in and now it does not work. Is there a config change we need to make?

**Comment by bobtwinkles** [comment]
@sichtbeton  it's live now at https://synthstromaudible.github.io/DelugeFirmware/

**Comment by sichtbeton** [comment]
maybe this can be put into the wiki or even the start page of the github on the righthand side?

**Pull request merged**
