### PR TITLE
Upgrade toolchain to v12

### PR DESCRIPTION
**Pull request by stellar-aria**

### CODE REVIEW

**Comment by stellar-aria** [comment]
Unfortunately removes `-ffreestanding` due to GNU toolchain limitations (lack of <cmath> being freestanding now being an [error](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=109814)), but there seems to be no pollution from symbols we wouldn't want (malloc/malloc_r/calloc), so this is a fixable problem for the future. Potentially with a custom libstdc++ based on picolibc.

**Comment by sapphire-arches** [comment]
```
1120204	  21144	 318712	1460060	 16475c	/src/build/Release/deluge-v1_1_0-dev+2024_01_23-d42e700.elf (base commit)
1117620	  21144	 318856	1457620	 163dd4	/src/build/Release/deluge-v1_1_0-dev+2024_01_23-010d28c.elf (this PR)
  -2584	      0	   +144	  -2440	 (deltas)
```

Quick voice test using the init synth, 1 note per 16th, with 50 release @ 150 BPM:
```
71-74 (d8d7c83c771ceee9b2a2f1b3eab8b47f373a0d38, this PR)
69-72 (d42e7002338a52886368924cc6a1b4aca6eaaee4)
```

Build times (unscientific):
```
d8d7c83c771ceee9b2a2f1b3eab8b47f373a0d38 (this PR)
real	0m49.185s
user	0m0.023s
sys	0m0.026s

d42e7002338a52886368924cc6a1b4aca6eaaee4 (HEAD)
real	0m48.527s
user	0m0.024s
sys	0m0.024s
```

The build feels slower, but i think it's because some stuff got moved to the pre-link LTO stage?

**Comment by stellar-aria** [comment]
> The build feels slower, but i think it's because some stuff got moved to the pre-link LTO stage?

Yeah, exactly, I think there's more optimizations in the LTO now? It's been a major focus of GCC for the last few versions.

**Review by m-m-adams — APPROVED** [review]
Seems good to me - no noticeable impact to performance in my test song

**Pull request merged**
