### PR TITLE
toolchain: single source of truth for required version

### PR DESCRIPTION
**Pull request by bobtwinkles**
this adds a file, `toolchain/REQUIRED_VERSION`, which acts as the source of truth for DBT and CI to pull the required toolchain version from.

I haven't tested this on Windows or OSX because I don't have those platforms, but at least the general shape should work.

### CODE REVIEW

**Comment by wright** [comment]
This builds OK on OSX.

**Comment by litui** [comment]
I can test it in windows later today. Thanks for doing this!

**Review by litui — APPROVED** [review]
Appears to work fine in Windows!

**Comment by jamiefaye** [comment]
Lets do this one and #68 soon!

**Pull request merged**
