### PR TITLE
chore: remove evil gotos

### PR DESCRIPTION
**Pull request by bobtwinkles**
The compiler can generate good code from the readable version. Tested on an OLED deluge.

### CODE REVIEW

**Comment by jamiefaye** [comment]
This one looks good, but I don't have my OLED unit back yet. Does anybody have one that can check this?

**Comment by litui** [comment]
Got one lingering conflict here. Once that's fixed, this can go through.

**Comment by jamiefaye** [comment]
Can you fix the conflict at src/oled.cpp? Then it can go in.

**Review by dctucker — APPROVED** [review]

**Comment by jamiefaye** [comment]
merged hopefully

**Pull request merged**
