### PR TITLE
Preserve Pad Brightness Preference Through Power Cycle

### PR DESCRIPTION
**Pull request by joxihan**

### CODE REVIEW

**Comment by stellar-aria** [comment]
Instead of having an explicit default brightness, can we just have setDimmerInterval instead store the newly set value in the FlashStorage, and do something to mark the settings as unsaved, and then save at a later point when there's nothing going on to be interrupted?

That way the last set brightness will simply persist across resets, rather than defaulting to a value that may not be correct for all situations.

**Comment by sapphire-arches** [comment]
I'm a little nervous about introducing implicit writes to flash from UI code, and retaining the ability to have transient as well as default brightness levels seems useful.

**Comment by m-m-adams** [comment]
I agree - having a default and a temporary value seems useful to me

**Comment by joxihan** [comment]
a bit confused, do i need to make a change or not at the end ? :p

**Comment by stellar-aria** [comment]
😅 Looks like I'm outvoted, in which case...

LGTM :shipit:

**Review by stellar-aria — APPROVED** [review]

**Pull request merged**
