### PR TITLE
ci: automatically push clang-format fixes

### PR DESCRIPTION
**Pull request by bobtwinkles**

### CODE REVIEW

**Comment by bobtwinkles** [comment]
Example commit of this working: https://github.com/bobtwinkles/DelugeFirmware/commit/1866cf1263e0989975cb639da17d0f942a918b6b

I'm not 100% sure if it'll work on a commit someone else makes yet.

**Comment by bobtwinkles** [comment]
Marking as draft for now because it doesn't work

**Comment by trappar** [comment]
IMO CI should block when there are linting/formatting issues rather than fixing them. Maybe this would be better as a pre-commit hook?

**Comment by bobtwinkles** [comment]
I did get a little caught up with about whether I could and didn't consider whether I should. The idea is to make it easier for people who don't want to deal with the formatter. 

This would likely be better served by a pre-commit hook, but those don't get installed by default (for good reason). I'll try to sketch one out to see how it goes.

**Comment by jamiefaye** [comment]
What I would like (personally, for me) is to have the system report that my
formatting needs to be fixed and to then have a button I push that goes
ahead and fixes it.

– Jamie

**Comment by m-m-adams** [comment]
I'd like to revisit this discussion - what about installing pre commit hooks via dbt and then having format be one of them?

**Comment by PaulFreund** [comment]
Hey, a quick heads up :) After two weeks without any activity from the author of a PR we tag it with the "stale" label and close it after another week of inactivity as per our [Contributor guidelins](https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/CONTRIBUTING.md?plain=1#L50). This is not to create pressure or discourage anyone but to keep the list of Pull requests maintainable.

We are very happy about your contribution and nothing will be lost. You can pick up the work at any time by reopening the PR or creating a new one.

**Pull request closed without merging**
