### PR TITLE
Stereo Chorus

### PR DESCRIPTION
**Pull request by alter-alter**
Added a stereo chorus effect to the MOD FXs

### CODE REVIEW

**Comment by litui** [comment]
@alter-alter heya! Thanks very much for the submission! I'll run workflows and see if we can get this tested and in soon =)

**Comment by jamiefaye** [comment]
This compiles OK on 7LED. I however have not figured out how to actually test this. The terms "MOD FX", "PHASER", and "FLANGER" do not appear in the index nor can I find this stuff in the 4.1.0 text.

Please humor this old lady and tell me how to get this working.

**Comment by m-m-adams** [comment]
Would it be possible to generalize this to add a second mod fx LFO at a slightly different rate and have it do stereo versions of all effects?

As is I think I hear phasing issues if I use the stereo chorus and then collapse to mono in a daw

**Comment by alter-alter** [comment]
> What builds have been tested on the Deluge hardware so far?

I have tested the release-OLED build.

**Comment by alter-alter** [comment]
> As is I think I hear phasing issues if I use the stereo chorus and then collapse to mono in a daw

I think phase problems are unlikely to occur because the pitch changes with the modulation of the delay time. (When the right channel rises in pitch, the left channel falls.)

**Comment by litui** [comment]
Congrats on the merge! We appreciate your contribution back to the community build.

**Comment by alter-alter** [comment]
Thanks!

**Pull request merged**
