### PR TITLE
[DRAFT] Accidental transposes of individual notes

### PR DESCRIPTION
**Pull request by jantuitman**
This is just a first start to create a placeholder PR, I still need to do a lot of work:

  - [x] saving/loading/datamodel in note. 

UI: editing
  - [x] being able to toggle between probability and accidentalTranspose
  - [x] fix encoder press handling.
  - [x] get current value and increment it/decrement it instead of -1,0,1
  - [x] display the note name instead of the +1,0, -1 value.
  - [x] handle multiple presses as well, and test cross screen editing. 
  
Note colours and displaying of accidental notes:
  - [x]  note colours, generate schemes that allow extra colours for expressing the transpose. (done but experimental for now).
  - [x]    note colours, refactor noteRow->renderRow (probably move it out to another file that knows about all the colors of all the rows. This will hopefully improve the code as well, as there is some duplication going on and diffuse responsibility between InstrumentClipView, Clip and NoteRow about who is in 'charge' of rendering.
 - [x] fix note color rendering in side buttons
 - [x] fix note color rendering in keyboard view 
 - [x] fix note color rendering in session view
 - [x] note color doesnt refresh when transposing.
 
Non ui tasks:
  - [x] make sure the accidentalTranspose attribute is used when playing the notes.
  - [ ] auditioning of transposed note.
  - [x] i only checked for note instance creation within NoteRow.cpp but i have to check if other files also create notes.

 
Current bugs:
   - [x] colors for kit tracks dont seem to work properly and the audition pad color doesnt correspond with the note color. in session view with classic the kit colours become a small gradient.
   - [x] the colors of classic theme for non kit views seem to be 2 octaves misaligned/rotated with respect the old colors.
   - [x] switching key (scale button) while the track is playing and there were notes with accidental transposes, sometimes causes the old notes not to be switched off.
   - [x] changing the transpose of a currently playing note may cause the note not to be switched off.

### CODE REVIEW

**Comment by jantuitman** [comment]
@jamiefaye you can remove confict label because i merged community branch today.

**Comment by PaulFreund** [comment]
Since not all tasks in your description are done it would make sense to convert this to a Draft PR. I think Jamie added the label because she thought it is ready for merging but not mergable.

**Comment by jantuitman** [comment]
> Since not all tasks in your description are done it would make sense to convert this to a Draft PR. I think Jamie added the label because she thought it is ready for merging but not mergable.

Ah, my bad. I put draft in the title, but I didn’t know GitHub had a state for it nowadays. So I converted it now to a draft PR

**Comment by PaulFreund** [comment]
Hey, a quick heads up :) After two weeks without any activity from the author of a PR we tag it with the "stale" label and close it after another week of inactivity as per our [Contributor guidelins](https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/CONTRIBUTING.md?plain=1#L50). This is not to create pressure or discourage anyone but to keep the list of Pull requests maintainable.

We are very happy about your contribution and nothing will be lost. You can pick up the work at any time by reopening the PR or creating a new one.

**Comment by jantuitman** [comment]
> Hey, a quick heads up :) After two weeks without any activity from the author of a PR we tag it with the "stale" label and close it after another week of inactivity as per our [Contributor guidelins](https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/CONTRIBUTING.md?plain=1#L50). This is not to create pressure or discourage anyone but to keep the list of Pull requests maintainable.
> 
> We are very happy about your contribution and nothing will be lost. You can pick up the work at any time by reopening the PR or creating a new one.

Thanks for the heads up, github apparently does not send notifications about these labels to me. I will resume soon. i had some holidays and after that some health issues which prevented me from working on this, but i think i will be able to continue this week.

**Comment by PaulFreund** [comment]
Hi @jantuitman thanks for the heads up and happy you feel better :) I don't want to be too strict about the stale period since you want to continue but if you change your mind please close it yourself so the list stays tidy, we can reopen any time!

**Comment by PaulFreund** [comment]
Since it has been another week without activity I hope you are okay with me closing the PR for now. Once you want to pick it up again we can reopen it or create a new one :)

**Pull request closed without merging**
