### PR TITLE
[DRAFT] Feature: Persistent User-Defined Pad Brightness Setting

### PR DESCRIPTION
**Pull request by alex-r-t**
## Summary
Allow the user to modify the pad brightness level and save the value to the flash or SD Card which should, in theory, prevent the user from having to reset the parameter after every reboot

### CODE REVIEW

**Comment by sichtbeton** [comment]
This is awsome!

**Comment by joxihan** [comment]
I didn't know there was a open PR on this topic. I have some code somewhat working don't know if Alex has done it already

**Comment by sichtbeton** [comment]
> I didn't know there was a open PR on this topic. I have some code somewhat working don't know if Alex has done it already

Alex wanted to work on this more, but (i am just guessing) time was too limited. Could your code be merged with Alex work? 

If not, could you open a new PR?

**Comment by joxihan** [comment]
> > I didn't know there was a open PR on this topic. I have some code somewhat working don't know if Alex has done it already
> 
> Alex wanted to work on this more, but (i am just guessing) time was too limited. Could your code be merged with Alex work?
> 
> If not, could you open a new PR?

there is no code change in this current draft ^^

**Comment by soymonitus** [comment]
@joxihan this PR hasn't had any activity in 3 months. If you have something already working i would post a new PR

**Comment by alex-r-t** [comment]
> @joxihan this PR hasn't had any activity in 3 months. If you have something already working i would post a new PR

Yep, I completely agree with this - let's start a new PR to make sure folks know progress is actually being made on this. Sorry for sitting on this so long

**Comment by alex-r-t** [comment]
For those that want to follow along: https://github.com/SynthstromAudible/DelugeFirmware/pull/1312

**Pull request closed without merging**
