### PR TITLE
Add additional reverb models

### PR DESCRIPTION
**Pull request by stellar-aria**
This adds additional reverb models based on the one present in Mutable Instruments' modules (Clouds/Rings/Beads) and Valley Rack's Plateau.

To-Do:
- [x] Add reverb models/code
- [x] Convert relevant code to run on Deluge from doubles to floats
- [x] Static sample rate conversion
- [x] Convert valley/LFO and mutable/cosine_oscillator to NEON accelerated oscillator blocks using Argon
- [x] Add additional Plateau-only parameters (pre-delay, modulator shape/speed/depth, LP/HP cutoff freqs, etc.)
- [x] Fix function names/style cleanup
- [ ] Optimizations
- [ ] Better overall integration

### CODE REVIEW

**Comment by worker-gray** [comment]
I apologize if this isn't the correct forum, but is a 'gated' reverb a possible addition? Like a reverb that would stop as soon as any input signal terminates.

**Comment by soymonitus** [comment]
Is this already testable (alpha)? I mean, does it have already menus to select and change the reverbs?

**Comment by stellar-aria** [comment]
> Is this already testable (alpha)? I mean, does it have already menus to select and change the reverbs?

The Mutable mode, yes, Plateau is currently broken and simply keeps running as Mutable. There's a new menu under Settings > FX > Reverb for "Mode[l]" that you can use to select the model type.

**Comment by ok-reza** [comment]
exciting development!
i think i'm noticing that WIDTH is being reset after adjusting that value and exiting the parameter menu. every time i re-enter it, it's back at 0.

**Comment by sichtbeton** [comment]
Mutable is beautiful.

plateau is kind of hard to get to grips with atm. It seems more of a delay than a reverb. 

Both share one flaw: a long reverb tail gets cut off after about 12 seconds. This seems to be a Deluge issue (as found out by the dev of this PR).

**Comment by Icoustic** [comment]
> Mutable is beautiful.
> 
> plateau is kind of hard to get to grips with atm. It seems more of a delay than a reverb.
> 
> Both share one flaw: a long reverb tail gets cut off after about 12 seconds. This seems to be a Deluge issue (as found out by the dev of this PR).

Haven't tested this yet but I've gotten splendid reverb sounds from Plateau in MiRack at least! The Diffuse setting can certainly make it sound more like individual taps though

**Comment by pssssssst** [comment]
Hi, is this still in nightly? I can't seem to find it.

**Comment by bobtwinkles** [comment]
This work is not yet merged, so it is not present in nightly or beta. Hopefully we can get it merged in the next couple of months.

**Comment by pssssssst** [comment]
Ahh, i see. i'll wait for it. enough other features to explore :) thanks

**Comment by soymonitus** [comment]
C'mon stellar-aria! you can make it, just the last mile! Looking forward to the plate reverb to be included in the build

**Comment by synthpatches** [comment]
I would like to test this feature, is it possible?

**Comment by sichtbeton** [comment]
> C'mon stellar-aria! you can make it, just the last mile! Looking forward to the plate reverb to be included in the build

+1

the plateau was incredible.

**Pull request closed without merging**
