### PR TITLE
DBT-Toolchain 8

### PR DESCRIPTION
**Pull request by litui**
- Enable DBT to pull new version of toolchain
- Toolchain adds: clang-format 14
- Toolchain removes: cmake
- Toolchain fixes: mac dotfiles should no longer be tarred.

### CODE REVIEW

**Comment by litui** [comment]
*looks at workflow failures* Ha... WELL, this is going to pose problems innit.

**Comment by litui** [comment]
Submitted PR https://github.com/bobtwinkles/deluge-ci-images/pull/1 to get the CI's DBT upgraded to 8 so we can upgrade `community`'s DBT to 8.  Maybe @bobtwinkles and I should look at integrating dbt-toolchain and the deluge-ci-images repos so this can be done in one pass. 🤔

**Comment by bobtwinkles** [comment]
The other thing I should fix is find a way to publish to tags other than `main` in the ci-images repo, so we can pull specific versions of the toolchain (instead of just pulling `main` all the time)

**Comment by bobtwinkles** [comment]
#89 switches the check workflow to use a versioned toolchain so things can be moved in lockstep.

**Pull request merged**
