### PR TITLE
WIP: profiler

### PR DESCRIPTION
**Pull request by bobtwinkles**
I want to add monitoring of cache health (L2C/L-320) and turn this in to either a runtime switch or a more accessible compile time option but it sort of works now.

### CODE REVIEW

**Comment by PaulFreund** [comment]
Hey, a quick heads up :) After two weeks without any activity from the author of a PR we tag it with the "stale" label and close it after another week of inactivity as per our [Contributor guidelins](https://github.com/SynthstromAudible/DelugeFirmware/blob/community/docs/CONTRIBUTING.md?plain=1#L50). This is not to create pressure or discourage anyone but to keep the list of Pull requests maintainable.

We are very happy about your contribution and nothing will be lost. You can pick up the work at any time by reopening the PR or creating a new one.

**Comment by jamiefaye** [comment]
Here is a patch to bring this up to date.
[diff316082923.patch](https://github.com/SynthstromAudible/DelugeFirmware/files/12469991/diff316082923.patch)

**Comment by PaulFreund** [comment]
@jamiefaye @bobtwinkles tomorrow stale period would expire, if you want to continue with this @jamiefaye I will close this PR and you can create a new one. Sounds good?

**Comment by PaulFreund** [comment]
I hope it is fine for everyone I close this PR for now, we can always create a new one or reopen it if someone wants to pick up the work :)

**Pull request closed without merging**
