### PR TITLE
remove UI::getName() as dead code

### PR DESCRIPTION
**Pull request by nikodemus**

### CODE REVIEW

**Comment by seangoodvibes** [comment]
Was this not added for debug purposes or to communicate to an external app what UI you're in?

**Comment by nikodemus** [comment]
> Was this not added for debug purposes or to communicate to an external app what UI you're in?

Oh, that makes sense -- but we also have getUIType()?

**Comment by seangoodvibes** [comment]
> > Was this not added for debug purposes or to communicate to an external app what UI you're in?
> 
> 
> 
> Oh, that makes sense -- but we also have getUIType()?

I added getUIType() to clean up some code internally in the codebase.

I think they serve a different purpose.

Are you able to see who added the UIName stuff? Maybe we can ask them or glean the reasoning from the PR.

**Comment by nikodemus** [comment]
> I added getUIType() to clean up some code internally in the codebase.
> 
> I think they serve a different purpose.
> 
> Are you able to see who added the UIName stuff? Maybe we can ask them or glean the reasoning from the PR.

It comes in here: https://github.com/SynthstromAudible/DelugeFirmware/commit/22cf36ea8ac92de962b213ed622ee77dd97c039b

use is:
```
+// This is a debug feature that allows us to output SYSEX debug logging button presses
+// See contributing.md for more information
+#if ENABLE_MATRIX_DEBUG
+       D_PRINT("UI=%s, Button=%s, On=%d", getCurrentUI()->getName(), getButtonName(b), on);
+#endif
```

While the usage of getUIType is different, it seems to me all UIs that have a name also have a distinct type. (Need to double-check, but also if not everything has a different type I'm not 100% convinced the debug output needs to distinguish between eg. rename_drum_ui and rename_clip_ui.)

I think I'd like to:

1) add a table that translates UI type to a name
2) conditionalize that table on the same ENABLE_MATRIX_DEBUG

-- or at minimum rename the method to getUIDebugName()

**Comment by seangoodvibes** [comment]
> > I added getUIType() to clean up some code internally in the codebase.
> 
> > 
> 
> > I think they serve a different purpose.
> 
> > 
> 
> > Are you able to see who added the UIName stuff? Maybe we can ask them or glean the reasoning from the PR.
> 
> 
> 
> It comes in here: https://github.com/SynthstromAudible/DelugeFirmware/commit/22cf36ea8ac92de962b213ed622ee77dd97c039b
> 
> 
> 
> use is:
> 
> ```
> 
> +// This is a debug feature that allows us to output SYSEX debug logging button presses
> 
> +// See contributing.md for more information
> 
> +#if ENABLE_MATRIX_DEBUG
> 
> +       D_PRINT("UI=%s, Button=%s, On=%d", getCurrentUI()->getName(), getButtonName(b), on);
> 
> +#endif
> 
> ```
> 
> 
> 
> While the usage of getUIType is different, it seems to me all UIs that have a name also have a distinct type. (Need to double-check, but also if not everything has a different type I'm not 100% convinced the debug output needs to distinguish between eg. rename_drum_ui and rename_clip_ui.)
> 
> 
> 
> I think I'd like to:
> 
> 
> 
> 1) add a table that translates UI type to a name
> 
> 2) conditionalize that table on the same ENABLE_MATRIX_DEBUG
> 
> 
> 
> -- or at minimum rename the method to getUIDebugName()

I like either of your approaches

**Comment by nikodemus** [comment]
closing for now, well resubmit later

**Pull request closed without merging**
