### PR TITLE
Streamline recording new clips while Deluge is playing

### PR DESCRIPTION
**Pull request by cowboy**
This assumes Deluge is in grid mode, Deluge is playing, and Rec is enabled.

The following steps assume default active is set to green, but should work regardless of how default active is set. The updated behavior works in green mode.

Instead of:

1. Hold blue mode button + long-press empty clip pad(s) to create clip(s)
2. Short-press clip(s) created in step 1 to queue them up for recording at the beginning of the next bar
3. Record clip(s)

This allows one to:

1. Short-press empty clip pad(s) to create clip(s) and queue them up for recording at the beginning of the next bar
2. Record clip(s)

In my testing, this makes recording new clips significantly easier.

### CODE REVIEW

**Comment by PaulFreund** [comment]
Hey there, really cool! :) Didn't look at the code yet but I'm sure a lot of people will find that useful. In order to properly integrate it I propose to change "Empty pad unarm" which is On/Off currently into "Empty pad action" where the user can select between Nothing, Unarm and Create+Record. What do you think?

In addition I am planning a red mode for punch in and punch out recording, if you are interested to pick it up you can highlight me and we can figure out the details on Discord.

**Comment by sichtbeton** [comment]
> Hey there, really cool! :) Didn't look at the code yet but I'm sure a lot of people will find that useful. In order to properly integrate it I propose to change "Empty pad unarm" which is On/Off currently into "Empty pad action" where the user can select between Nothing, Unarm and Create+Record. What do you think?
> 
> In addition I am planning a red mode for punch in and punch out recording, if you are interested to pick it up you can highlight me and we can figure out the details on Discord.

Question: couldn’t these two functions coexist? They are differentiated by rec enabled.

**Comment by cowboy** [comment]
To @sichtbeton 's point, I actually use both unarm and create+record together. I've added a few commits which create a "Empty pads" submenu with independent "Unarm" and "Create + Record" bool toggles.

**Comment by PaulFreund** [comment]
Ah very nice, that works for me as well :) Once you are ready feel free to request a review after converting from Draft to ready.

**Comment by cowboy** [comment]
There's nothing else I want to add to this PR, so I think it's ready for review. I hope others will test it, in case I missed anything important!

**Review by PaulFreund — APPROVED** [review]
Just a reminder that currentSong->currentClip will need to be updated later

**Comment by cowboy** [comment]
> Just a reminder that currentSong->currentClip will need to be updated later

See https://github.com/SynthstromAudible/DelugeFirmware/pull/973

**Comment by solaris76** [comment]
Minor one; Documentation 'a' should read as below: ("SONG" missing). 
Enter SETTINGS > DEFAULTS > UI > SONG > GRID > EMPTY PADS > CREATE + RECORD and select ENABLED

**Pull request merged**
