### PR TITLE
[Draft] Show value (expressed in the range 0-127) of golden knobs (anywhere: affect-entire song mode, synths, midi clips..)

### PR DESCRIPTION
**Pull request by soymonitus**
Useful to get a quick and dirty reference of where the hell are you. Besides, it matches the value that you would set if you midi learn that golden know to a Midi CC. A must for setting delay amount just max at value 63 (64 will have feedback till you get deaf…). Good also for changing global song-level affect-entire golden knobs which you can’t see the values they have anywhere.

https://youtu.be/npixC97l-uw

### CODE REVIEW

**Comment by PaulFreund** [comment]
Hey really love this! I know numericDriver is really easy but any chance we use the same display as editing synth parameters here? It would also show you what is edited. Your video also matches what I propose in #274

**Comment by soymonitus** [comment]
> Hey really love this! I know numericDriver is really easy but any chance we use the same display as editing synth parameters here? It would also show you what is edited. Your video also matches what I propose in #274

I found that getting the real value was quite hidden and that the modEncodetAction only has information about the knob position and the converted int32 value (which has nothing to do with the range 0-50 seen in some parameters.
So i though that maybe to simplify code and not build a custom function for every different parameter in every different screen (sounds like a lot of work), the possibility to show just the encoder value in its range (which is -64 to 64, which is converted to 0-127 for readability and similarity with Midi CC values) . In fact, what I only did was move the code that showed midi cc for midi clips to the parent so it works also for every other clip type.

**Comment by soymonitus** [comment]
I still need to fix that when you are editing a parameter, for example Pan, and it appears in the screen with values -32 to 32, if you turn the corresponding golden knob it shows the popup over the real value, and it should not show the popup if the real value is behind. Maybe I need to take a look to a more complex implementation where it takes into account the parameter being edited and shows the same UI as when you do shift+shorcut pad

**Comment by seangoodvibes** [comment]
Damn this is awesome and coincidentally in line with exactly what im doing in my automation lanes PR. i am showing 0-127 any time you turn gold knobs.

**Comment by soymonitus** [comment]
I think so too, showing the actual value and parameter name needs lots of coding

**Comment by soymonitus** [comment]
Maybe someone could help me add to the popup the name of the parameter (only for OLED, as a two lines popup, and just the value for 7seg)

**Comment by seangoodvibes** [comment]
@soymonitus I looked at your code. I don't think this is the right way to implement this change.

The function you modified is used everywhere in the codebase to do calculations of the current parameter's knob position/parameter value. 

This will have unwanted consequences across the codebase any time this calculation function is called. We will get popups like crazy.

I don't recommend merging this until further thought is taken as to how to make such a change. 

Sorry this has wider implications!

**Comment by soymonitus** [comment]
I will try to address it in a different way. Thanks for the feedback

**Comment by seangoodvibes** [comment]
@soymonitus could you also change your PR to draft until it is ready to be merged :)? Thanks!

**Comment by soymonitus** [comment]
Can someone help pointing me in the right direction. I am in the modEncoderAction function in view.cpp and I feel the code should be there but I need to find which parameter is the golden knob editing, if there is an object I can access to know the printable name and the value range

**Comment by seangoodvibes** [comment]
> Can someone help pointing me in the right direction. I am in the modEncoderAction function in view.cpp and I feel the code should be there but I need to find which parameter is the golden knob editing, if there is an object I can access to know the printable name and the value range

Hey so I'm not sure about the value range, but this is one function I use get to the parameter display name, but its only for Patched Params..(there's unpatched ones too...)

char const* getPatchedParamDisplayNameForOled(int p) {

You have to pass it a Parameter ID

Midi would be a bit different since you have to pass it the Midi CC control number, and this function helps draw what Midi CC you're editing:

void InstrumentClipMinder::drawMIDIControlNumber(int controlNumber, bool automationExists) {

---

I think view.modEncoderAction is the right function, so you're on the right track

newKnobPos + 64 is going to hold the value you want to display

---

To get the ParamID/controlNumber...

There are a bunch of functions to get the paramID from the knob, I'm not exactly sure which one you'll need, since I know you can also learn params to those knobs which makes thing tricker. And there's different types of params (patched vs unpatched) And if you're in a Midi Clip it's different also.

These are some I found:

int GlobalEffectableForClip::getParameterFromKnob(int whichModEncoder) {
int GlobalEffectable::getParameterFromKnob(int whichModEncoder) {

Sorry I can't be anymore help right now.

Hope this guides you in the right direction!!

**Comment by soymonitus** [comment]
> > Can someone help pointing me in the right direction. I am in the modEncoderAction function in view.cpp and I feel the code should be there but I need to find which parameter is the golden knob editing, if there is an object I can access to know the printable name and the value range
> 
> Hey so I'm not sure about the value range, but this is one function I use get to the parameter display name, but its only for Patched Params..(there's unpatched ones too...)
> 
> char const* getPatchedParamDisplayNameForOled(int p) {
> 
> You have to pass it a Parameter ID
> 
> Midi would be a bit different since you have to pass it the Midi CC control number, and this function helps draw what Midi CC you're editing:
> 
> void InstrumentClipMinder::drawMIDIControlNumber(int controlNumber, bool automationExists) {
> 
> I think view.modEncoderAction is the right function, so you're on the right track
> 
> newKnobPos + 64 is going to hold the value you want to display
> 
> To get the ParamID/controlNumber...
> 
> There are a bunch of functions to get the paramID from the knob, I'm not exactly sure which one you'll need, since I know you can also learn params to those knobs which makes thing tricker. And there's different types of params (patched vs unpatched) And if you're in a Midi Clip it's different also.
> 
> These are some I found:
> 
> int GlobalEffectableForClip::getParameterFromKnob(int whichModEncoder) { int GlobalEffectable::getParameterFromKnob(int whichModEncoder) {
> 
> Sorry I can't be anymore help right now.
> 
> Hope this guides you in the right direction!!

This is superhelpful. Thanks a lot for taking the time to answer

**Comment by m-m-adams** [comment]
I don't really use the delay but does it start to feedback continuously past 63, and still have adjustments up until 127? That seems like maybe the range should be tweaked lol

**Comment by m-m-adams** [comment]
I just want to leave a mention that this was an intentional design decision on the deluge, it's talked about in Rohan's interview in the book push, turn, move. The idea was that you would just see the LED bars and not need to look at the screen.


If the exact value makes that big a difference for the delay maybe it should be set to flash at 63 like pan and eq do?

**Comment by sichtbeton** [comment]
> I just want to leave a mention that this was an intentional design decision on the deluge, it's talked about in Rohan's interview in the book push, turn, move. The idea was that you would just see the LED bars and not need to look at the screen.
> 
> If the exact value makes that big a difference for the delay maybe it should be set to flash at 63 like pan and eq do?

good idea. also maybe having an option to remove this (feedback part) would be good. it can get annoying pretty fast and can destroy a live set. so having this optional would not only prevent that but also provide a more detailed delay dialing mechanism (much larger knob reach).

**Comment by seangoodvibes** [comment]
Just wanted to mention:

The knob position range is actually 0-128 (-64 to +64 internally)

**Comment by soymonitus** [comment]
Closing as I will not work on this for a while

**Pull request closed without merging**
