### PR TITLE
Arpeggiator param saving for Midi clips fixed

### PR DESCRIPTION
**Pull request by soymonitus**
Fixes https://github.com/SynthstromAudible/DelugeFirmware/issues/1633

NOTE: To cherry pick!

Existing songs created with previous versions of 1.1 beta may need to go into arp settings of their MIDI clips and update the params to avoid crashes, as they are now in the range 0-50 instead of full integer.

### CODE REVIEW

**Comment by m-m-adams** [comment]
Stick to saving/loading in the full param range. This will make it unnecessarily more complicated to integrate with other deluge parameter systems in the future

**Comment by soymonitus** [comment]
> Stick to saving/loading in the full param range. This will make it unnecessarily more complicated to integrate with other deluge parameter systems in the future 

I tried to stick to full range ints but, i had a problem
In which existing values like Gate whose default value is 25 are fine but for values whose default value should be zero i have a problem. When multiplying the range 0-50 by 85899345 as you see in some parts of the code, it doesn't reach the maximum integer value, but 22 units less. When the center value is 25, equivalent to zero in the signed int32 range (as Gate and Rate use) that 22 unit diff is spread equally between each half of the integer range, in a way that the conversion from full int range is, minimum value is 0 and max value is 50. I tried making it start from minimum int so the default value is 0 and not 25 like Gate, but i found the problem that values are converted (rounded) as 1 unit less. For example, i set Rhythm value to 5, and when entering again the menu option and reading it, i see value 4. I set value 23 and i enter again and see 22. Etc. Do you know what i mean? Should i do some logic to make values default to zero if value is not present in the XML?

**Comment by m-m-adams** [comment]
Maybe take a look at how the pan parameter gets converted to display as +-25? I think it would have the same complexities

**Comment by soymonitus** [comment]
> Maybe take a look at how the pan parameter gets converted to display as +-25? I think it would have the same complexities

I have checked how Pan (unpatched param) is programmed and was surprised to find it to have a min and max values of -25 and 25 and have not conversion logic in the pan.h class. What am I missing...?:

namespace deluge::gui::menu_item::unpatched_param {

class Pan final : public UnpatchedParam {
public:
	using UnpatchedParam::UnpatchedParam;
	virtual void drawValue();

protected:
	[[nodiscard]] int32_t getMaxValue() const override { return kMaxMenuRelativeValue; }
	[[nodiscard]] int32_t getMinValue() const override { return kMinMenuRelativeValue; }
	int32_t getFinalValue() override;
	void readCurrentValue() override;
};
} // namespace deluge::gui::menu_item::unpatched_param

**Comment by soymonitus** [comment]
@m-m-adams Fixed it with something even more simple from what I thought! It was a casting problem thing (uint32 vs int32). So I reverted all my funky changes and applied just the small fix

**Review by m-m-adams — APPROVED** [review]

**Pull request merged**
